



-- =========== PROJECT ON INDIAN CENSUS DATA 2011    ========

CREATE DATABASE INDIAN_CENSUS_2011;
USE INDIAN_CENSUS_2011;
SHOW DATABASES;
SHOW TABLES;

SELECT*FROM DATASET1;
SELECT*FROM DATASET_2;

-- ======= QUERY ======

-- Q1. TOTAL NO OF ROWS IN DATASET?
	SELECT*FROM DATASET1;
    
    SELECT COUNT(*) FROM DATASET1; #640
    
    SELECT COUNT(DISTRICT) FROM DATASET1; #640 "YOU CAN USE '*' OR ANY COLUMN NAME IN COUNT"
    
    SELECT*FROM DATASET_2;
    SELECT COUNT(*) FROM DATASET_2; #640
    
    SELECT COUNT(POPULATION) FROM DATASET_2; #640
    
    
    
-- Q2. SHOW DATA  ONLY FOR JHARKHAND AND BIHAR?
	SELECT*FROM DATASET1 ORDER BY STATE;
    
    SELECT DISTRICT,STATE FROM DATASET1; #USE THIS TO SELECT ONLY PERTICULAR COLUMN
    
	SELECT*FROM DATASET1  WHERE STATE="JHARKHAND";   #24 ROWS
    
    SELECT*FROM DATASET1 WHERE STATE="JHARKHAND" AND STATE="BIHAR";  #0 ROWS
    
	SELECT*FROM DATASET1 WHERE STATE="BIHAR"; #38 ROWS
    
	SELECT*FROM DATASET1 WHERE STATE="BIHAR" OR STATE="JHARKHAND"; #62 ROWS
    
    SELECT*FROM DATASET1 WHERE STATE IN("JHARKHAND", "BIHAR"); #62 ROWS "ALTERNET QUERY"
    
    SELECT*FROM DATASET_2 ORDER BY STATE;
    
    SELECT*FROM DATASET_2 WHERE STATE="JHARKHAND"; #23 ROWS
    
	SELECT*FROM DATASET_2 WHERE STATE="BIHAR";  #36 ROWS
    
	SELECT*FROM DATASET_2 WHERE STATE="JHARKHAND" AND STATE="BIHAR"; #0
    
	SELECT*FROM DATASET_2 WHERE STATE="JHARKHAND" OR STATE="BIHAR";  #59 ROWS
    
    SELECT*FROM DATASET_2 WHERE STATE IN("JHARKHAND", "BIHAR"); #59 ROWS "ALTERNET QUERY"
    
    
    
-- Q3. POLULATION OF INDIA IN 2011?
-- POLULATION COLUMN IS PRESENT IN DATASET_2 SO USE IT
	
    SELECT*FROM DATASET_2;
    SELECT SUM(Population) AS "TOTAL POPULATION OF INDIA" FROM DATASET_2;
    
    SELECT SUM(POPULATION) FROM DATASET_2; #SHOWING WRONG GO THROUGH IT
    
    SELECT SUM(AREA_KM2) FROM DATASET_2;   #SHOWING WRONG GO THROUGH IT
    
    SELECT*FROM DATASET1;
    SELECT SUM(SEX_RATIO) FROM DATASET1; #605077
    SELECT SUM(SEX_RATIO) AS "TOTAL SEX RATIO" FROM DATASET1;  #605077 it is used to give name for column
    SELECT SUM(SEX_RATIO) AS TOTAL_SEX_RATIO_OF_INDIA FROM DATASET1;  #605077
    SELECT SUM(GROWTH) FROM DATASET1; #12317.39
    SELECT SUM(LITERACY) FROM DATASET1;  #46277.38
    
    
    
-- Q4. WHAT IS AVG GROWTH OF POPULATION IN INDIA IN 2011?
-- USE DATABASE1
-- NOTE: "AVG" AGGREGATE IS DEPENDENT AGGREGATE "SUM,MAX,MIN,COUNT" ARE INDEPENDENT AGGREGATES.

	SELECT*FROM DATASET1;
    
    SELECT AVG(GROWTH) AS "AVG GROWTH OF POPULATION" FROM DATASET1;  #19.2459
    
    SELECT AVG(GROWTH) AVG_GROWTHOF_POPULATION FROM DATASET1;  #19.2459  
    
	SELECT AVG(GROWTH) AS AVG_GROWTHOF_POPULATION FROM DATASET1;  #19.2459 THIS IS IN PERCENTAGE
    
	SELECT AVG(GROWTH)/100 AS AVG_GROWTHOF_POPULATION FROM DATASET1;  #0.19245 "IF WE WANT IN FLOAT THEN USE THIS"
    
    
    
-- Q5. AVG GROWTH BY STATE

	SELECT*FROM DATASET1;
    SELECT STATE, AVG(GROWTH) AS AVG_GROWTH FROM DATASET1 GROUP BY STATE;
    
	SELECT STATE, AVG(GROWTH) AS AVG_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY STATE; #COMBINE BY STATE AND IN ACSENDING ORDER
    
	SELECT STATE, AVG(GROWTH) AS AVG_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY STATE ASC;
    
    SELECT STATE, AVG(GROWTH) AS AVG_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY STATE DESC; #IN DESCINDING OREDER
    
    
    
-- Q6 AVG SEX_RATIO BY STATE

	SELECT*FROM DATASET1;
    SELECT STATE, AVG(SEX_RATIO) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE;
    
    SELECT STATE, AVG(SEX_RATIO) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE ORDER BY STATE;
    
	SELECT STATE, AVG(SEX_RATIO) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE ORDER BY STATE DESC;
    
	SELECT STATE, ROUND(AVG(SEX_RATIO),0) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE ORDER BY STATE; #"ROUND" USED TO ROUND IT TO PERTICULAT DECIMAL
    
	SELECT STATE, ROUND(AVG(SEX_RATIO),2) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE;
    
    
-- Q7 AVG LITERACY RATE

	SELECT*FROM DATASET1;
    SELECT AVG(LITERACY) AS AVG_LITERACY_RATE FROM DATASET1;  #72.308 "TOTAL AVG LITERACY RATE"
    
    SELECT STATE, AVG(LITERACY) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE; #"LITERACY RATE BY STATE"
    
	SELECT STATE, AVG(LITERACY) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY STATE;
    
    SELECT STATE, AVG(LITERACY) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE HAVING AVG(LITERACY)>60 ORDER BY STATE;
    
	SELECT STATE, AVG(LITERACY) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY STATE DESC;
    # NOTE: IF YOU SELECT ANY COLUMN AT STARTING (EX: STATE,) STATE THEN YOU HAVE TO TAKE ORDER BY CLAUSE
	
    SELECT STATE, ROUND(AVG(LITERACY), 2) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY STATE;
    
    SELECT STATE, ROUND(AVG(LITERACY), 0) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY STATE;
    
	SELECT STATE, ROUND(AVG(LITERACY), 0) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY STATE LIMIT 5;
    
	SELECT STATE, ROUND(AVG(LITERACY), 0) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE
    HAVING ROUND(AVG(LITERACY), 0) >90 ORDER BY STATE;
    
    # NOTE: SQL QUERY ALWAYS WRITE IN ORDER LIKE 1ST "SELECT" THEN "ORDER BY" THEN "HAVING" AT THE LAST "ORDER BY"
    
    
-- Q8. TOP 3 STATE SHOWING HIGHEST GROWTH RATIO, LITERACY

	SELECT STATE, AVG(GROWTH) AS AVG_OF_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY AVG_OF_GROWTH DESC LIMIT 3;
    
    SELECT STATE, ROUND(AVG(LITERACY),2) AS AVG_OF_LITERACY FROM DATASET1 GROUP BY STATE ORDER BY AVG_OF_LITERACY DESC LIMIT 3;
    
    
-- Q9. bottom 3 STATE SHOWING LOWEST GROWTH RATIO , SEX RATIO, LITERACY

	SELECT STATE, AVG(GROWTH) AS AVG_OF_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY AVG_OF_GROWTH LIMIT 3;
    
	SELECT STATE, ROUND(AVG(GROWTH), 2) AS AVG_OF_GROWTH FROM DATASET1 GROUP BY STATE ORDER BY AVG_OF_GROWTH LIMIT 3;
    
    SELECT STATE, ROUND(AVG(SEX_RATIO), 2) AS AVG_SEX_RATIO FROM DATASET1 GROUP BY STATE ORDER BY AVG_SEX_RATIO LIMIT 3;
    
    SELECT STATE, ROUND(AVG(LITERACY), 2) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY AVG_LITERACY_RATE LIMIT 3;
    
    
-- Q10. TOP AND BOTTOM 3 STATE IN LITERACY RATE? 

	(SELECT STATE, ROUND(AVG(LITERACY),2) AS AVG_OF_LITERACY FROM DATASET1 GROUP BY STATE ORDER BY AVG_OF_LITERACY DESC LIMIT 3)
    UNION 
    (SELECT STATE, ROUND(AVG(LITERACY), 2) AS AVG_LITERACY_RATE FROM DATASET1 GROUP BY STATE ORDER BY AVG_LITERACY_RATE LIMIT 3);
    
    

-- Q11. STATES STARTING WITH ALPHABAT "A" END WITH "A"

	SELECT * FROM DATASET1 WHERE STATE LIKE 'A%'; 
    SELECT * FROM DATASET1 WHERE STATE LIKE "%A";
    SELECT * FROM DATASET1 WHERE STATE LIKE "%A%";
    
	SELECT DISTINCT STATE FROM DATASET1 WHERE STATE LIKE 'A%'; #4
	SELECT DISTINCT STATE FROM DATASET1 WHERE STATE LIKE '%A'; #8
    
    SELECT DISTINCT STATE FROM DATASET1 WHERE STATE LIKE "A%" OR STATE LIKE"%D";
    

    
   
    

    
    

	





	

	
    

    
    







